/*

 *     Rex
 */
package justdemo;

import javax.swing.ImageIcon;

/**
 *
 * @author Regis
 */
public class RegisterPage extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titletext = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        email_id = new javax.swing.JTextField();
        phoneNo = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        lastNamePersonIcon = new javax.swing.JLabel();
        passwordIcon = new javax.swing.JLabel();
        emailIdIcon = new javax.swing.JLabel();
        personIcon = new javax.swing.JLabel();
        phoneNoIcon = new javax.swing.JLabel();
        confirmPasswordIcon = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        createButton = new javax.swing.JLabel();
        MiddleRectangle = new javax.swing.JLabel();
        MainBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        Titletext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/titleText.png"))); // NOI18N
        getContentPane().add(Titletext);
        Titletext.setBounds(520, 50, 370, 70);

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        getContentPane().add(firstName);
        firstName.setBounds(560, 140, 290, 40);
        getContentPane().add(lastName);
        lastName.setBounds(560, 210, 290, 40);
        getContentPane().add(email_id);
        email_id.setBounds(560, 340, 290, 40);
        getContentPane().add(phoneNo);
        phoneNo.setBounds(560, 270, 290, 40);
        getContentPane().add(password);
        password.setBounds(560, 400, 290, 40);
        getContentPane().add(confirmPassword);
        confirmPassword.setBounds(560, 460, 290, 40);

        lastNamePersonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/personIcon.png"))); // NOI18N
        getContentPane().add(lastNamePersonIcon);
        lastNamePersonIcon.setBounds(480, 140, 39, 40);

        passwordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/lockIcon.png"))); // NOI18N
        getContentPane().add(passwordIcon);
        passwordIcon.setBounds(490, 460, 33, 35);

        emailIdIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/mailicon.png"))); // NOI18N
        getContentPane().add(emailIdIcon);
        emailIdIcon.setBounds(480, 340, 62, 36);

        personIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/personIcon.png"))); // NOI18N
        getContentPane().add(personIcon);
        personIcon.setBounds(480, 210, 39, 40);

        phoneNoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/phoneIcon.png"))); // NOI18N
        getContentPane().add(phoneNoIcon);
        phoneNoIcon.setBounds(480, 260, 57, 50);

        confirmPasswordIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/lockIcon.png"))); // NOI18N
        getContentPane().add(confirmPasswordIcon);
        confirmPasswordIcon.setBounds(490, 400, 40, 40);

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/clearbutton.png"))); // NOI18N
        getContentPane().add(clear);
        clear.setBounds(720, 540, 284, 57);

        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/createAccount.png"))); // NOI18N
        getContentPane().add(createButton);
        createButton.setBounds(380, 540, 283, 58);

        MiddleRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/newWhiteBackground.png"))); // NOI18N
        getContentPane().add(MiddleRectangle);
        MiddleRectangle.setBounds(320, 50, 708, 570);

        MainBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/justdemo/images/ss.png"))); // NOI18N
        getContentPane().add(MainBackground);
        MainBackground.setBounds(0, 0, 1370, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       ImageIcon image = new ImageIcon(getClass().getResource("\\images\\ss.png"));
        MainBackground.setIcon(image);
    }//GEN-LAST:event_formWindowOpened

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainBackground;
    private javax.swing.JLabel MiddleRectangle;
    private javax.swing.JLabel Titletext;
    private javax.swing.JLabel clear;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel confirmPasswordIcon;
    private javax.swing.JLabel createButton;
    private javax.swing.JLabel emailIdIcon;
    private javax.swing.JTextField email_id;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNamePersonIcon;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordIcon;
    private javax.swing.JLabel personIcon;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JLabel phoneNoIcon;
    // End of variables declaration//GEN-END:variables
}
